language: node_js
node_js:
  - "8"
before_install:
  - git config --global push.default matching
  - git config --global user.name "erguotou"
  - git config --global user.email "erguotou525@gmail.com"
install:
  - npm install -g gitbook-cli
script:
  - gitbook build
  - cd _book
  - git init
  - git add -A
  - git commit -m "Auto build"
  - git push -u https://$GH_TOKEN@github.com/weexplus/doc.git HEAD:gh-pages --force
cache:
  directories:
    - $(npm config get prefix)/gitbook-cli
